version: '3.8'

services:
  messenger:
    build: .
    container_name: secure_chat_node
    restart: always
    volumes:
      - ./uploads:/app/uploads
      - db_data:/app/db_data # Создаем новую, вечную папку для базы данных
    ports:
      - "5000:5000"

  caddy:
    image: caddy:2.7-alpine
    container_name: caddy_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - messenger

volumes:
  caddy_data:
  caddy_config:
  db_data: # Объявляем вечный диск